//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportProduct.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int id { get; set; }
        public string article { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> SizeMaxSale { get; set; }
        public string NameCreater { get; set; }
        public string NameShop { get; set; }
        public string CategoryProduct { get; set; }
        public Nullable<int> ActivSale { get; set; }
        public Nullable<int> CountSale { get; set; }
        public string InfoProduct { get; set; }
        public string Image { get; set; }
    }
}
